main: com.kryeit.LambdaStuff
version: 1.0
author: MuriPlz
api-version: 1.20
softdepend: [AFKPlus,GriefDefender]
name: LambdaStuff
commands:
  online:
    description: online players
    permission: stuff.online
  discord:
    description: manda el link de discord
  reglas:
    description: manda el link de las reglas
  mandarcoordenadas:
    description: manda tus coordenadas a un jugador
  mapa:
    description: manda una url del mapa interactivo
  tiempojugado:
    description: enseña el tiempo jugado de un jugador
  ultimaconexion:
    description: enseña la última conexión
  fly:
    description: makes you fly
    permission: stuff.fly
  invsee:
    description: gets a player inventory
    permission: stuff.invsee
  enderinvsee:
    description: gets a player enderchest
    permission: stuff.enderinvsee