main: com.kryeit.Stuff
version: 1.1
author: MuriPlz
api-version: 1.18
depend: [AFKPlus,GriefDefender]
name: Stuff
commands:
  vr:
    description: Voting for my server rewards
  online:
    description: online players
    permission: stuff.online
  discord:
    description: sends discord link
  forum:
    description: sends forum link
  rules:
    description: sends rules link
  sendcoords:
    description: sends your cords to the player
  map:
    description: shows dynmap url
  vote:
    description: sends planetminecraft link
  patreon:
    description: sends patreon link
    aliases:
      - donate
  timeplayed:
    description: shows time played
  lastonline:
    description: shows last time online
  fly:
    description: makes you fly
    permission: stuff.fly
  mute:
    description: mutes players
    permission: stuff.mute
  getinventory:
    description: gets a player inventory
    permission: stuff.getinventory